# Generated by Django 5.2.7 on 2025-12-03 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='criminals/')),
                ('missing_place', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Police_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Missing_Child_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=255)),
                ('CASE_REPORT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.case_report')),
                ('POLICE_STATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.police_station')),
            ],
        ),
        migrations.CreateModel(
            name='Public_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='captured_image/')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('MISSING_CHILD_DATA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.missing_child_data')),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='user_id_proof/')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=255)),
                ('reply', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(max_length=255)),
                ('USER_PROFILE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_profile')),
            ],
        ),
        migrations.AddField(
            model_name='case_report',
            name='USER_PROFILE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_profile'),
        ),
    ]
