# Generated by Django 5.2.3 on 2025-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_awareness_case_report_dress_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
